add gammastep

diff --git a/.local/bin/sway/gstep b/.local/bin/sway/gstep
--- a/.local/bin/sway/gstep
+++ b/.local/bin/sway/gstep
@@ -35,7 +35,7 @@ case "$1" in
 	stop) stop ;;
 	toggle) toggle ;;
 	*)
-		echo "error: bad command" >&2
+		echo "error: unexpected command" >&2
 		exit 1
 esac
 
